# Generated by Django 4.2 on 2023-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='size',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
