# Generated by Django 4.2 on 2023-04-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_prodictimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdictImage',
            new_name='ProductImage',
        ),
    ]
