# Generated by Django 4.2 on 2023-04-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_productsize_size_productsize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgender',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='productgender',
            name='gender',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='size_name', to='store.size'),
        ),
        migrations.AddField(
            model_name='productgender',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgender',
            name='gender',
            field=models.ManyToManyField(to='store.gender'),
        ),
    ]
