# Generated by Django 4.2 on 2023-05-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_productgender_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizeprice',
            name='product_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_name', to='store.productcategory'),
        ),
    ]
