# Generated by Django 4.2 on 2023-05-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_productsizeprice_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgender',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='productgender',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='ProductGender',
        ),
    ]
