# Generated by Django 4.2 on 2023-05-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_productgender_product_and_more'),
        ('cart', '0002_cart_product_price_cart_quantity_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_color',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.productcolor'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_size',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.DO_NOTHING, to='store.productsize'),
        ),
    ]
