# Generated by Django 4.2 on 2023-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_product_color_alter_cart_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
