# Generated by Django 4.2 on 2023-05-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_productgender_product_and_more'),
        ('cart', '0006_alter_cart_productsizeprice_alter_cart_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productSizePrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productsizeprice'),
        ),
    ]
