# Generated by Django 4.2 on 2023-05-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_productsizeprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='productSizePrice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_price',
        ),
    ]
